spring:
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=lms
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


api:
  info:
    title: university
    description: University system
    version: 1.0
    terms-of-service: https://unicorn.pdp.uz
    contact-name: pdp.uz
    contact-email: saidjalolqodirov1@gmail.com
    contact-url: https://pdp.uz
    license-name: Apache 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui

properties:
  when:
    type: string
    format: date-time